### ISSUE TITLE
vortigaunt sweep elevator glitch

### ISSUE THREAD

**Issue by tonybalogne** [vingard/impulse-issues#55]
**Describe the bug**
If you're going down on any elevator, if you left click with broom, you will float in the air for the duration of the sweeping animation, and then fall back down.

**To reproduce**
Steps to reproduce the behaviour:
Go to an elevator and go down on it (not up)
Equip broom
Press left click
You are now floating

**Expected behaviour**
I expected to just go down with the elevator, but I'm pretty sure you just made the broom freeze the playermodel and play an animation when you left click, but made it so your unable to sweep in the air to prevent floating. But it doesn't really work on elevators

**Screenshots**
Pretty self explanatory 

**impulse version (press F1 in the bottom right):**
1.34
**Lua error**

**Additional context**
The last elevator up to the CA's office, if you go down it and left click you will take fall damage because it goes down pretty fast

**Comment by vingard** [comment]
Internally we use freezing as a hacky way to make sure animations are played at their base speed in the Source engine for long animations like sweeping (the engine multiplies animation speed by velocity). As a result this does freeze you mid-air, however I included a check so you can only trigger these animations when you are on the ground. Technically when you are in a lift you are on the ground still so this check doesn't work. Because it's such a small issue I won't patch it as I can't really fix it fully anyway. Thanks for the report anyway.
