### ISSUE TITLE
XP bug

### ISSUE THREAD

**Issue by 1avx1** [vingard/impulse-issues#85]
**Describe the bug**
You get XP if you join the server and go AFK immediately after you joined

**To reproduce**
Steps to reproduce the behaviour:
1. Join the server
2. Don't click on anything when it says "Press any key to continue" screen
3. Go AFK

**Expected behaviour**
You shouldn't receive XP if you joined the server and didn't press "Play" at all.

**Screenshots**
None

**impulse version (press F1 in the bottom right):**
1.61

**Lua error**
None

**Additional context**
impulse broken vin pliz fix uwu

**Comment by ATLIEN101** [comment]
yeah i got into the game and i went somewhere else and let the game load and when it loaded i still wasn't  on my pc i was in the other room and when  i saw it was loaded and i press random key to load in and then i had  much more xp then before  because i had like 19.500 XP last time i played and now when  i joined i had like 19,598 XP

**Comment by BlizzardBoi** [comment]
You can’t get to 8 XP, it’s impossible to get to that number.

**Comment by vingard** [comment]
Fixed in 1.62, thanks! :)
